# Configuration
cidr_block: 10.10.0.0/16
---
# Template
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: {{ cidr_block }}
Outputs:
    VPCID:
        Value: !Ref VPC
---
# Stack metadata
stack_name: vpc
---
# Raw template
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.10.0.0/16
Outputs:
    VPCID:
        Value: !Ref VPC
        Export:
            Name: vpc-VPCID
